/**
 * Copyright (C) 2017 OPTiM Corp. All Rights Reserved
 * システム名：
 * ソースファイル名：CompanyManagement.java
 */

package cloud.optim.aivoiceanalytics.api.entity;
// Generated by Hibernate Tools 3.2.2.CR1


import java.util.Date;

/**

 */
public class CompanyManagement  implements java.io.Serializable {


	/**
	 * 企業管理 ID
	 */
	private Long companyManagementId;

	/**
	 * 更新日時
	 */
	private Date updateDate;

	/**
	 * 企業 ID
	 */
	private String companyId;

	/**
	 * 企業名
	 */
	private String companyName;

	/**
	 * 代理店企業ID
	 */
	private String agencyCompanyId;

	/**
	 * リカイアスライセンスID
	 */
	private Long recaiusLicenseId;

	/**
	 * リカイアスモデルID
	 */
	private Integer recaiusModelId;

	/**
	 * 音声判断レベル閾値
	 */
	private Integer energyThreshold;

	/**
	 * 音声保存設定
	 */
	private Boolean saveVoice;

	/**
	 * 接続元制限IPアドレス
	 */
	private String permitIpAddress;

	/**
	 * 音声ファイル保存日数
	 */
	private Integer voiceKeepDays;

	/**
	 * 論理削除ログ保存日数
	 */
	private Integer logicalDeleteLogKeepDays;

	/**
	 * 作成日時
	 */
	private Date createDate;

	/**
	 * 作成ユーザ ID
	 */
	private String createUserId;

	/**
	 * 作成ユーザ名
	 */
	private String createUserName;

	/**
	 * 更新ユーザ ID
	 */
	private String updateUserId;

	/**
	 * 更新ユーザ名
	 */
	private String updateUserName;


	/**
	 * CompanyManagement デフォルトコンストラクター
	 */
	public CompanyManagement() {
	}

	/**
	 * CompanyManagement 最小コンストラクター
	 * @param companyId 企業 ID
	 * @param agencyCompanyId 代理店企業ID
	 * @param recaiusLicenseId リカイアスライセンスID
	 * @param recaiusModelId リカイアスモデルID
	 * @param energyThreshold 音声判断レベル閾値
	 * @param createDate 作成日時
	 * @param createUserId 作成ユーザ ID
	 * @param createUserName 作成ユーザ名
	 * @param updateUserId 更新ユーザ ID
	 * @param updateUserName 更新ユーザ名
	 */
	public CompanyManagement(String companyId, String agencyCompanyId, Long recaiusLicenseId, Integer recaiusModelId, Integer energyThreshold, Date createDate, String createUserId, String createUserName, String updateUserId, String updateUserName) {
		this.companyId = companyId;
		this.agencyCompanyId = agencyCompanyId;
		this.recaiusLicenseId = recaiusLicenseId;
		this.recaiusModelId = recaiusModelId;
		this.energyThreshold = energyThreshold;
		this.createDate = createDate;
		this.createUserId = createUserId;
		this.createUserName = createUserName;
		this.updateUserId = updateUserId;
		this.updateUserName = updateUserName;
    }
	/**
	 * CompanyManagement フルコンストラクター
	 * @param companyId 企業 ID
	 * @param companyName 企業名
	 * @param agencyCompanyId 代理店企業ID
	 * @param recaiusLicenseId リカイアスライセンスID
	 * @param recaiusModelId リカイアスモデルID
	 * @param energyThreshold 音声判断レベル閾値
	 * @param saveVoice 音声保存設定
	 * @param permitIpAddress 接続元制限IPアドレス
	 * @param voiceKeepDays 音声ファイル保存日数
	 * @param logicalDeleteLogKeepDays 論理削除ログ保存日数
	 * @param createDate 作成日時
	 * @param createUserId 作成ユーザ ID
	 * @param createUserName 作成ユーザ名
	 * @param updateUserId 更新ユーザ ID
	 * @param updateUserName 更新ユーザ名
	 */
	public CompanyManagement(String companyId, String companyName, String agencyCompanyId, Long recaiusLicenseId, Integer recaiusModelId, Integer energyThreshold, Boolean saveVoice, String permitIpAddress, Integer voiceKeepDays, Integer logicalDeleteLogKeepDays, Date createDate, String createUserId, String createUserName, String updateUserId, String updateUserName) {
		this.companyId = companyId;
		this.companyName = companyName;
		this.agencyCompanyId = agencyCompanyId;
		this.recaiusLicenseId = recaiusLicenseId;
		this.recaiusModelId = recaiusModelId;
		this.energyThreshold = energyThreshold;
		this.saveVoice = saveVoice;
		this.permitIpAddress = permitIpAddress;
		this.voiceKeepDays = voiceKeepDays;
		this.logicalDeleteLogKeepDays = logicalDeleteLogKeepDays;
		this.createDate = createDate;
		this.createUserId = createUserId;
		this.createUserName = createUserName;
		this.updateUserId = updateUserId;
		this.updateUserName = updateUserName;
	}

	// * 企業管理 ID */
	/**
	 * @return companyManagementId (企業管理 ID)
	 */
	public Long getCompanyManagementId() {
		return this.companyManagementId;
	}

	/**
	 * @param companyManagementId 企業管理 ID
	 */
	public void setCompanyManagementId(Long companyManagementId) {
		this.companyManagementId = companyManagementId;
	}

	// * 更新日時 */
	/**
	 * @return updateDate (更新日時)
	 */
	public Date getUpdateDate() {
		return this.updateDate;
	}

	/**
	 * @param updateDate 更新日時
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	// * 企業 ID */
	/**
	 * @return companyId (企業 ID)
	 */
	public String getCompanyId() {
		return this.companyId;
	}

	/**
	 * @param companyId 企業 ID
	 */
	public void setCompanyId(String companyId) {
		this.companyId = companyId;
	}

	// * 企業名 */
	/**
	 * @return companyName (企業名)
	 */
	public String getCompanyName() {
		return this.companyName;
	}

	/**
	 * @param companyName 企業名
	 */
	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	// * 代理店企業ID */
	/**
	 * @return agencyCompanyId (代理店企業ID)
	 */
	public String getAgencyCompanyId() {
		return this.agencyCompanyId;
	}

	/**
	 * @param agencyCompanyId 代理店企業ID
	 */
	public void setAgencyCompanyId(String agencyCompanyId) {
		this.agencyCompanyId = agencyCompanyId;
	}

	// * リカイアスライセンスID */
	/**
	 * @return recaiusLicenseId (リカイアスライセンスID)
	 */
	public Long getRecaiusLicenseId() {
		return this.recaiusLicenseId;
	}

	/**
	 * @param recaiusLicenseId リカイアスライセンスID
	 */
	public void setRecaiusLicenseId(Long recaiusLicenseId) {
		this.recaiusLicenseId = recaiusLicenseId;
	}

	// * リカイアスモデルID */
	/**
	 * @return recaiusModelId (リカイアスモデルID)
	 */
	public Integer getRecaiusModelId() {
		return this.recaiusModelId;
	}

	/**
	 * @param recaiusModelId リカイアスモデルID
	 */
	public void setRecaiusModelId(Integer recaiusModelId) {
		this.recaiusModelId = recaiusModelId;
	}

	// * 音声判断レベル閾値 */
	/**
	 * @return energyThreshold (音声判断レベル閾値)
	 */
	public Integer getEnergyThreshold() {
		return this.energyThreshold;
	}

	/**
	 * @param energyThreshold 音声判断レベル閾値
	 */
	public void setEnergyThreshold(Integer energyThreshold) {
		this.energyThreshold = energyThreshold;
	}

	// * 音声保存設定 */
	/**
	 * @return saveVoice (音声保存設定)
	 */
	public Boolean getSaveVoice() {
		return this.saveVoice;
	}

	/**
	 * @param saveVoice 音声保存設定
	 */
	public void setSaveVoice(Boolean saveVoice) {
		this.saveVoice = saveVoice;
	}

	// * 接続元制限IPアドレス */
	/**
	 * @return permitIpAddress (接続元制限IPアドレス)
	 */
	public String getPermitIpAddress() {
		return this.permitIpAddress;
	}

	/**
	 * @param permitIpAddress 接続元制限IPアドレス
	 */
	public void setPermitIpAddress(String permitIpAddress) {
		this.permitIpAddress = permitIpAddress;
	}

	// * 音声ファイル保存日数 */
	/**
	 * @return voiceKeepDays (音声ファイル保存日数)
	 */
	public Integer getVoiceKeepDays() {
		return this.voiceKeepDays;
	}

	/**
	 * @param voiceKeepDays 音声ファイル保存日数
	 */
	public void setVoiceKeepDays(Integer voiceKeepDays) {
		this.voiceKeepDays = voiceKeepDays;
	}

	// * 論理削除ログ保存日数 */
	/**
	 * @return logicalDeleteLogKeepDays (論理削除ログ保存日数)
	 */
	public Integer getLogicalDeleteLogKeepDays() {
		return this.logicalDeleteLogKeepDays;
	}

	/**
	 * @param logicalDeleteLogKeepDays 論理削除ログ保存日数
	 */
	public void setLogicalDeleteLogKeepDays(Integer logicalDeleteLogKeepDays) {
		this.logicalDeleteLogKeepDays = logicalDeleteLogKeepDays;
	}

	// * 作成日時 */
	/**
	 * @return createDate (作成日時)
	 */
	public Date getCreateDate() {
		return this.createDate;
	}

	/**
	 * @param createDate 作成日時
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	// * 作成ユーザ ID */
	/**
	 * @return createUserId (作成ユーザ ID)
	 */
	public String getCreateUserId() {
		return this.createUserId;
	}

	/**
	 * @param createUserId 作成ユーザ ID
	 */
	public void setCreateUserId(String createUserId) {
		this.createUserId = createUserId;
	}

	// * 作成ユーザ名 */
	/**
	 * @return createUserName (作成ユーザ名)
	 */
	public String getCreateUserName() {
		return this.createUserName;
	}

	/**
	 * @param createUserName 作成ユーザ名
	 */
	public void setCreateUserName(String createUserName) {
		this.createUserName = createUserName;
	}

	// * 更新ユーザ ID */
	/**
	 * @return updateUserId (更新ユーザ ID)
	 */
	public String getUpdateUserId() {
		return this.updateUserId;
	}

	/**
	 * @param updateUserId 更新ユーザ ID
	 */
	public void setUpdateUserId(String updateUserId) {
		this.updateUserId = updateUserId;
	}

	// * 更新ユーザ名 */
	/**
	 * @return updateUserName (更新ユーザ名)
	 */
	public String getUpdateUserName() {
		return this.updateUserName;
	}

	/**
	 * @param updateUserName 更新ユーザ名
	 */
	public void setUpdateUserName(String updateUserName) {
		this.updateUserName = updateUserName;
	}


	/**
	 * toString
	 * @return String
	*/
	public String toString() {
		StringBuffer buffer = new StringBuffer();

		buffer.append(getClass().getName()).append("@").append(Integer.toHexString(hashCode())).append(" [");
		buffer.append("companyManagementId").append("='").append(getCompanyManagementId()).append("' ");
		buffer.append("updateDate").append("='").append(getUpdateDate()).append("' ");
		buffer.append("companyId").append("='").append(getCompanyId()).append("' ");
		buffer.append("agencyCompanyId").append("='").append(getAgencyCompanyId()).append("' ");
		buffer.append("recaiusModelId").append("='").append(getRecaiusModelId()).append("' ");
		buffer.append("energyThreshold").append("='").append(getEnergyThreshold()).append("' ");
		buffer.append("saveVoice").append("='").append(getSaveVoice()).append("' ");
		buffer.append("permitIpAddress").append("='").append(getPermitIpAddress()).append("' ");
		buffer.append("voiceKeepDays").append("='").append(getVoiceKeepDays()).append("' ");
		buffer.append("logicalDeleteLogKeepDays").append("='").append(getLogicalDeleteLogKeepDays()).append("' ");
		buffer.append("createDate").append("='").append(getCreateDate()).append("' ");
		buffer.append("createUserId").append("='").append(getCreateUserId()).append("' ");
		buffer.append("updateUserId").append("='").append(getUpdateUserId()).append("' ");
		buffer.append("]");

		return buffer.toString();
	}

	@Override
	public boolean equals(Object other) {
		if ( (this == other ) ) return true;
		if ( (other == null ) ) return false;
		if ( !(other instanceof CompanyManagement) ) return false;
		CompanyManagement castOther = ( CompanyManagement ) other;

		return ( (this.getCompanyManagementId()==castOther.getCompanyManagementId()) || ( this.getCompanyManagementId()!=null && castOther.getCompanyManagementId()!=null && this.getCompanyManagementId().equals(castOther.getCompanyManagementId()) ) )
 && ( (this.getUpdateDate()==castOther.getUpdateDate()) || ( this.getUpdateDate()!=null && castOther.getUpdateDate()!=null && this.getUpdateDate().equals(castOther.getUpdateDate()) ) )
 && ( (this.getCompanyId()==castOther.getCompanyId()) || ( this.getCompanyId()!=null && castOther.getCompanyId()!=null && this.getCompanyId().equals(castOther.getCompanyId()) ) )
 && ( (this.getCompanyName()==castOther.getCompanyName()) || ( this.getCompanyName()!=null && castOther.getCompanyName()!=null && this.getCompanyName().equals(castOther.getCompanyName()) ) )
 && ( (this.getAgencyCompanyId()==castOther.getAgencyCompanyId()) || ( this.getAgencyCompanyId()!=null && castOther.getAgencyCompanyId()!=null && this.getAgencyCompanyId().equals(castOther.getAgencyCompanyId()) ) )
 && ( (this.getRecaiusLicenseId()==castOther.getRecaiusLicenseId()) || ( this.getRecaiusLicenseId()!=null && castOther.getRecaiusLicenseId()!=null && this.getRecaiusLicenseId().equals(castOther.getRecaiusLicenseId()) ) )
 && ( (this.getRecaiusModelId()==castOther.getRecaiusModelId()) || ( this.getRecaiusModelId()!=null && castOther.getRecaiusModelId()!=null && this.getRecaiusModelId().equals(castOther.getRecaiusModelId()) ) )
 && ( (this.getEnergyThreshold()==castOther.getEnergyThreshold()) || ( this.getEnergyThreshold()!=null && castOther.getEnergyThreshold()!=null && this.getEnergyThreshold().equals(castOther.getEnergyThreshold()) ) )
 && ( (this.getSaveVoice()==castOther.getSaveVoice()) || ( this.getSaveVoice()!=null && castOther.getSaveVoice()!=null && this.getSaveVoice().equals(castOther.getSaveVoice()) ) )
 && ( (this.getPermitIpAddress()==castOther.getPermitIpAddress()) || ( this.getPermitIpAddress()!=null && castOther.getPermitIpAddress()!=null && this.getPermitIpAddress().equals(castOther.getPermitIpAddress()) ) )
 && ( (this.getVoiceKeepDays()==castOther.getVoiceKeepDays()) || ( this.getVoiceKeepDays()!=null && castOther.getVoiceKeepDays()!=null && this.getVoiceKeepDays().equals(castOther.getVoiceKeepDays()) ) )
 && ( (this.getLogicalDeleteLogKeepDays()==castOther.getLogicalDeleteLogKeepDays()) || ( this.getLogicalDeleteLogKeepDays()!=null && castOther.getLogicalDeleteLogKeepDays()!=null && this.getLogicalDeleteLogKeepDays().equals(castOther.getLogicalDeleteLogKeepDays()) ) )
 && ( (this.getCreateDate()==castOther.getCreateDate()) || ( this.getCreateDate()!=null && castOther.getCreateDate()!=null && this.getCreateDate().equals(castOther.getCreateDate()) ) )
 && ( (this.getCreateUserId()==castOther.getCreateUserId()) || ( this.getCreateUserId()!=null && castOther.getCreateUserId()!=null && this.getCreateUserId().equals(castOther.getCreateUserId()) ) )
 && ( (this.getCreateUserName()==castOther.getCreateUserName()) || ( this.getCreateUserName()!=null && castOther.getCreateUserName()!=null && this.getCreateUserName().equals(castOther.getCreateUserName()) ) )
 && ( (this.getUpdateUserId()==castOther.getUpdateUserId()) || ( this.getUpdateUserId()!=null && castOther.getUpdateUserId()!=null && this.getUpdateUserId().equals(castOther.getUpdateUserId()) ) )
 && ( (this.getUpdateUserName()==castOther.getUpdateUserName()) || ( this.getUpdateUserName()!=null && castOther.getUpdateUserName()!=null && this.getUpdateUserName().equals(castOther.getUpdateUserName()) ) );
	}

	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + ( getCompanyManagementId() == null ? 0 : this.getCompanyManagementId().hashCode() );
		result = 37 * result + ( getUpdateDate() == null ? 0 : this.getUpdateDate().hashCode() );
		result = 37 * result + ( getCompanyId() == null ? 0 : this.getCompanyId().hashCode() );
		result = 37 * result + ( getCompanyName() == null ? 0 : this.getCompanyName().hashCode() );
		result = 37 * result + ( getAgencyCompanyId() == null ? 0 : this.getAgencyCompanyId().hashCode() );
		result = 37 * result + ( getRecaiusLicenseId() == null ? 0 : this.getRecaiusLicenseId().hashCode() );
		result = 37 * result + ( getRecaiusModelId() == null ? 0 : this.getRecaiusModelId().hashCode() );
		result = 37 * result + ( getEnergyThreshold() == null ? 0 : this.getEnergyThreshold().hashCode() );
		result = 37 * result + ( getSaveVoice() == null ? 0 : this.getSaveVoice().hashCode() );
		result = 37 * result + ( getPermitIpAddress() == null ? 0 : this.getPermitIpAddress().hashCode() );
		result = 37 * result + ( getVoiceKeepDays() == null ? 0 : this.getVoiceKeepDays().hashCode() );
		result = 37 * result + ( getLogicalDeleteLogKeepDays() == null ? 0 : this.getLogicalDeleteLogKeepDays().hashCode() );
		result = 37 * result + ( getCreateDate() == null ? 0 : this.getCreateDate().hashCode() );
		result = 37 * result + ( getCreateUserId() == null ? 0 : this.getCreateUserId().hashCode() );
		result = 37 * result + ( getCreateUserName() == null ? 0 : this.getCreateUserName().hashCode() );
		result = 37 * result + ( getUpdateUserId() == null ? 0 : this.getUpdateUserId().hashCode() );
		result = 37 * result + ( getUpdateUserName() == null ? 0 : this.getUpdateUserName().hashCode() );
		return result;
	}

  // The following is extra code specified in the hbm.xml files

	/** serialVersionUID  */
	private static final long serialVersionUID = 1L;
		
  // end of extra code specified in the hbm.xml files

}


