create table TBL_T_AGENCY (AGENCY_ID bigint not null auto_increment comment 'レコードの主キー',
		UPDATE_DATE datetime(3) not null comment '',
		AGENCY_COMPANY_ID varchar(32) not null comment '',
		CREATE_DATE datetime(3) not null comment '',
		CREATE_USER_ID varchar(32) not null comment '',
		CREATE_USER_NAME varchar(100) not null comment '',
		UPDATE_USER_ID varchar(32) not null comment '',
		UPDATE_USER_NAME varchar(100) not null comment '',
		primary key (AGENCY_ID),
		unique (AGENCY_COMPANY_ID)) comment='代理店' ENGINE=InnoDB;
create table TBL_T_COMPANY_MANAGEMENT (COMPANY_MANAGEMENT_ID bigint not null auto_increment comment 'レコードの主キー',
		UPDATE_DATE datetime(3) not null comment '',
		COMPANY_ID varchar(32) not null comment '',
		COMPANY_NAME varchar(100) comment '',
		AGENCY_COMPANY_ID varchar(32) not null comment '',
		RECAIUS_LICENSE_ID bigint not null comment '',
		RECAIUS_MODEL_ID integer not null comment '',
		ENERGY_THRESHOLD integer not null comment '0～1000',
		SAVE_VOICE bit comment 'true:音声解析時に音声ファイルを保存する false:音声解析時に音声ファイルの保存をしない',
		PERMIT_IP_ADDRESS varchar(3000) comment 'TEXT型で定義する',
		VOICE_KEEP_DAYS integer comment '',
		LOGICAL_DELETE_LOG_KEEP_DAYS integer comment '',
		CREATE_DATE datetime(3) not null comment '',
		CREATE_USER_ID varchar(32) not null comment '',
		CREATE_USER_NAME varchar(100) not null comment '',
		UPDATE_USER_ID varchar(32) not null comment '',
		UPDATE_USER_NAME varchar(100) not null comment '',
		primary key (COMPANY_MANAGEMENT_ID),
		unique (COMPANY_ID)) comment='企業管理' ENGINE=InnoDB;
create table TBL_T_RECAIUS_LICENSE (RECAIUS_LICENSE_ID bigint not null auto_increment comment 'レコードの主キー',
		UPDATE_DATE datetime(3) not null comment '',
		SERVICE_ID varchar(300) not null comment '',
		PASSWORD varchar(300) not null comment '',
		AGENCY_COMPANY_ID varchar(32) comment '',
		CREATE_DATE datetime(3) not null comment '',
		CREATE_USER_ID varchar(32) not null comment '',
		CREATE_USER_NAME varchar(100) not null comment '',
		UPDATE_USER_ID varchar(32) not null comment '',
		UPDATE_USER_NAME varchar(100) not null comment '',
		primary key (RECAIUS_LICENSE_ID),
		unique (SERVICE_ID)) comment='リカイアスライセンス' ENGINE=InnoDB;
create table TBL_T_SPEECH_LOG (SPEECH_LOG_ID bigint not null auto_increment comment 'レコードの主キー',
		UPDATE_DATE datetime(3) not null comment '',
		COMPANY_ID varchar(32) not null comment '',
		USER_ID varchar(32) not null comment '音声解析していた担当者',
		USER_NAME varchar(100) not null comment '',
		SPEECH_LOG_NO bigint not null comment '企業ごとの一連番号 （登録時に最大値＋1を設定）',
		TYPE varchar(2) not null comment '0：マイク 1：ファイル　',
		FILE_NAME varchar(256) comment '',
		START_DATE datetime(3) not null comment '',
		END_DATE datetime(3) not null comment '開始時は開始日時と同じ値を設定',
		CREATE_DATE datetime(3) not null comment '',
		CREATE_USER_ID varchar(32) not null comment '',
		CREATE_USER_NAME varchar(100) not null comment '',
		UPDATE_USER_ID varchar(32) not null comment '',
		UPDATE_USER_NAME varchar(100) not null comment '',
		DELETE_DATE datetime(3) comment '',
		primary key (SPEECH_LOG_ID),
		unique (COMPANY_ID,
		SPEECH_LOG_NO)) comment='音声解析ログ' ENGINE=InnoDB;
create table TBL_T_SPEECH_LOG_DETAIL (SPEECH_LOG_DETAIL_ID bigint not null auto_increment comment 'レコードの主キー',
		UPDATE_DATE datetime(3) not null comment '',
		COMPANY_ID varchar(32) not null comment '',
		SPEECH_LOG_ID bigint not null comment '',
		LOG longtext not null comment 'LONGTEXT 使用',
		BEGIN integer comment 'ミリ秒',
		END integer comment 'ミリ秒',
		VOICE_EXISTENCE bit not null comment 'false：無、true：有',
		CREATE_DATE datetime(3) not null comment '',
		CREATE_USER_ID varchar(32) not null comment '',
		CREATE_USER_NAME varchar(100) not null comment '',
		UPDATE_USER_ID varchar(32) not null comment '',
		UPDATE_USER_NAME varchar(100) not null comment '',
		DELETE_DATE datetime(3) comment '',
		primary key (SPEECH_LOG_DETAIL_ID)) comment='音声解析ログ詳細' ENGINE=InnoDB;
create table TBL_T_USE_TIME (USE_TIME_ID bigint not null auto_increment comment 'レコードの主キー',
		UPDATE_DATE datetime(3) not null comment '',
		COMPANY_ID varchar(32) not null comment '',
		COMPANY_NAME varchar(100) comment '',
		USER_ID varchar(32) not null comment '',
		USER_NAME varchar(100) not null comment '',
		TYPE varchar(2) not null comment '1：音声解析　2：要約',
		START_DATE datetime(3) not null comment '',
		END_DATE datetime(3) not null comment '開始時は開始日時と同じ値を設定',
		USE_TIME bigint not null comment '単位：ミリ秒／登録時に 0 を設定',
		CREATE_DATE datetime(3) not null comment '',
		CREATE_USER_ID varchar(32) not null comment '',
		CREATE_USER_NAME varchar(100) not null comment '',
		UPDATE_USER_ID varchar(32) not null comment '',
		UPDATE_USER_NAME varchar(100) not null comment '',
		primary key (USE_TIME_ID)) comment='利用時間' ENGINE=InnoDB;
create table TBL_T_VOICE_ENCODE_QUEUE (VOICE_ENCODE_QUEUE_ID bigint not null auto_increment comment 'レコードの主キー',
		UPDATE_DATE datetime(3) not null comment '',
		COMPANY_ID varchar(32) not null comment '',
		SPEECH_LOG_ID bigint not null comment '',
		SPEECH_LOG_DETAIL_ID bigint not null comment '',
		CREATE_DATE datetime(3) not null comment '',
		CREATE_USER_ID varchar(32) not null comment '',
		CREATE_USER_NAME varchar(100) not null comment '',
		primary key (VOICE_ENCODE_QUEUE_ID)) comment='音声解析音声圧縮キュー' ENGINE=InnoDB;
create index IDX_COMPANY_MANAGEMENT on TBL_T_COMPANY_MANAGEMENT (COMPANY_ID);
create index IDX_SPEECHLOG_COMPANY on TBL_T_SPEECH_LOG (COMPANY_ID);
create index IDX_SPEECHLOGDTL_COMPANY on TBL_T_SPEECH_LOG_DETAIL (COMPANY_ID);
create index IDX_USETIME_START_DATE on TBL_T_USE_TIME (START_DATE);
create index IDX_USETIME_END_DATE on TBL_T_USE_TIME (END_DATE);
create index IDX_USETIME_COMPANY on TBL_T_USE_TIME (COMPANY_ID);
create index IDX_VOICEENCODEQ_COMPANY on TBL_T_VOICE_ENCODE_QUEUE (COMPANY_ID);
